const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#7C3AED",
    background: "#F8F7FF",
    foreground: "#0a0a0a",
    card: "#FFFFFF",
    cardForeground: "#0a0a0a",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#F3F0FF",
    secondaryForeground: "#4C1D95",
    muted: "#F0EEFF",
    mutedForeground: "#6B7280",
    accent: "#F97316",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E0FF",
    input: "#E5E0FF",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#A78BFA",
    background: "#0A0A0F",
    foreground: "#F5F5FF",
    card: "#13131A",
    cardForeground: "#F5F5FF",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A2E",
    secondaryForeground: "#C4B5FD",
    muted: "#1A1A24",
    mutedForeground: "#888899",
    accent: "#F97316",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E2A",
    input: "#1A1A2E",
  },
  radius: 12,
};

export default colors;
