const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#8B5CF6",
    background: "#F8F7FF",
    foreground: "#0a0a0a",
    card: "#FFFFFF",
    cardForeground: "#0a0a0a",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#F3F0FF",
    secondaryForeground: "#4C1D95",
    muted: "#F0EEFF",
    mutedForeground: "#6B7280",
    accent: "#F97316",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E0FF",
    input: "#E5E0FF",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#8B5CF6",
    background: "#080810",
    foreground: "#FFFFFF",
    card: "#0F0F1A",
    cardForeground: "#FFFFFF",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#13131F",
    secondaryForeground: "#C4B5FD",
    muted: "#13131F",
    mutedForeground: "#9CA3AF",
    accent: "#F97316",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "rgba(255,255,255,0.08)",
    input: "#13131F",
  },
  radius: 16,
};

export default colors;
