uploads = []
outputs = []

[[generated]]
id = "F80vqSawGB6z1YKL6avtZ"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-PPzPN6GokYJbgoLTjjb6"
uri = "file://artifacts/mobile/assets/images/post1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zW1jlIwVPHNeKNaTD-XsD"
uri = "file://artifacts/mobile/assets/images/post2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "3tw41hCJpiPoJDdxaxhtm"
uri = "file://artifacts/mobile/assets/images/post3.png"
type = "image"
title = "generated_image"
