import { Router, type IRouter } from "express";
import healthRouter from "./health";
import aiCaptionRouter from "./ai/caption";
import aiChatRouter from "./ai/chat";
import pexelsTrendingRouter from "./pexels/trending";
import pexelsVideosRouter from "./pexels/videos";
import adminSetupRouter from "./admin/setup";
import musicDeezerRouter from "./music/deezer";
import postsCreateRouter from "./posts/create";
import reelsCreateRouter from "./reels/create";
import reelsWatchRouter from "./reels/watch";
import usersSearchRouter from "./users/search";
import usersSocialRouter from "./users/social";
import usersNotificationsRouter from "./users/notifications";
import engageRouter from "./engage";
import messagesRouter from "./messages";
import usersSetupRouter from "./users/setup";
import moderationRouter from "./moderation";
import storiesRouter from "./stories";
import commentsRouter from "./comments";
import storageRouter from "./storage";
import feedRouter from "./feed";
import vibeRouter from "./vibe";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/ai", aiCaptionRouter);
router.use("/ai", aiChatRouter);
router.use("/pexels", pexelsTrendingRouter);
router.use("/pexels/videos", pexelsVideosRouter);
router.use("/admin", adminSetupRouter);
router.use("/music", musicDeezerRouter);
router.use("/posts", postsCreateRouter);
router.use("/reels", reelsCreateRouter);
router.use("/reels", reelsWatchRouter);
router.use("/users", usersSearchRouter);
router.use("/users/social", usersSocialRouter);
router.use("/users/notifications", usersNotificationsRouter);
router.use("/engage", engageRouter);
router.use("/messages", messagesRouter);
router.use("/users", usersSetupRouter);
router.use("/moderation", moderationRouter);
router.use("/stories", storiesRouter);
router.use("/comments", commentsRouter);
router.use("/storage", storageRouter);
router.use("/feed", feedRouter);
router.use("/vibe", vibeRouter);

export default router;
