import { Router, type IRouter } from "express";
import healthRouter from "./health";
import aiCaptionRouter from "./ai/caption";
import aiChatRouter from "./ai/chat";
import postsRemoveRouter from "./posts/remove";
import adminSetupRouter from "./admin/setup";
import musicDeezerRouter from "./music/deezer";
import postsCreateRouter from "./posts/create";
import reelsCreateRouter from "./reels/create";
import reelsRemoveRouter from "./reels/remove";
import reelsWatchRouter from "./reels/watch";
import reelsLikeRouter from "./reels/like";
import usersSearchRouter from "./users/search";
import usersSocialRouter from "./users/social";
import usersNotificationsRouter from "./users/notifications";
import engageRouter from "./engage";
import messagesRouter from "./messages";
import usersSetupRouter from "./users/setup";
import moderationRouter from "./moderation";
import storiesRouter from "./stories";
import commentsRouter from "./comments";
import storageRouter from "./storage";
import feedRouter from "./feed";
import vibeRouter from "./vibe";
import vibeRequestsRouter from "./vibe-requests";
import vibeRoomsRouter from "./vibe-rooms";
import snapsRouter from "./snaps";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/ai", aiCaptionRouter);
router.use("/ai", aiChatRouter);
router.use("/admin", adminSetupRouter);
router.use("/music", musicDeezerRouter);
router.use("/posts", postsRemoveRouter);
router.use("/posts", postsCreateRouter);
router.use("/reels", reelsCreateRouter);
router.use("/reels", reelsRemoveRouter);
router.use("/reels", reelsWatchRouter);
router.use("/reels", reelsLikeRouter);
router.use("/users", usersSearchRouter);
router.use("/users/social", usersSocialRouter);
router.use("/users/notifications", usersNotificationsRouter);
router.use("/engage", engageRouter);
router.use("/messages", messagesRouter);
router.use("/users", usersSetupRouter);
router.use("/moderation", moderationRouter);
router.use("/stories", storiesRouter);
router.use("/comments", commentsRouter);
router.use("/storage", storageRouter);
router.use("/feed", feedRouter);
router.use("/vibe", vibeRouter);
router.use("/vibe-requests", vibeRequestsRouter);
router.use("/vibe-rooms", vibeRoomsRouter);
router.use("/snaps", snapsRouter);

export default router;
