import { Router, type IRouter } from "express";
import healthRouter from "./health";
import aiCaptionRouter from "./ai/caption";
import aiChatRouter from "./ai/chat";
import postsRemoveRouter from "./posts/remove";
import postsUpdateRouter from "./posts/update";
import adminSetupRouter from "./admin/setup";
import musicDeezerRouter from "./music/deezer";
import postsCreateRouter from "./posts/create";
import reelsCreateRouter from "./reels/create";
import reelsRemoveRouter from "./reels/remove";
import reelsWatchRouter from "./reels/watch";
import reelsLikeRouter from "./reels/like";
import usersSearchRouter from "./users/search";
import usersSocialRouter from "./users/social";
import usersNotificationsRouter from "./users/notifications";
import engageRouter from "./engage";
import messagesRouter from "./messages";
import usersSetupRouter from "./users/setup";
import moderationRouter from "./moderation";
import didRouter from "./did";
import storiesRouter from "./stories";
import commentsRouter from "./comments";
import storageRouter from "./storage";
import feedRouter from "./feed";
import vibeRouter from "./vibe";
import vibeRequestsRouter from "./vibe-requests";
import vibeRoomsRouter from "./vibe-rooms";
import snapsRouter from "./snaps";
import rewardsRouter from "./rewards";
import analyticsRouter from "./analytics";
import adsRouter from "./ads";
import liveRouter from "./live";
import usersOnboardingRouter from "./users/onboarding";
import usersContactsRouter from "./users/contacts";
import soundsRouter from "./sounds";
import coupleRouter from "./couple";
import coupleFeedRouter from "./couple-feed";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/ai", aiCaptionRouter);
router.use("/ai", aiChatRouter);
router.use("/admin", adminSetupRouter);
router.use("/music", musicDeezerRouter);
router.use("/posts", postsRemoveRouter);
router.use("/posts", postsUpdateRouter);
router.use("/posts", postsCreateRouter);
router.use("/reels", reelsCreateRouter);
router.use("/reels", reelsRemoveRouter);
router.use("/reels", reelsWatchRouter);
router.use("/reels", reelsLikeRouter);
router.use("/users", usersSearchRouter);
router.use("/users/social", usersSocialRouter);
router.use("/users/notifications", usersNotificationsRouter);
router.use("/engage", engageRouter);
router.use("/messages", messagesRouter);
router.use("/users", usersSetupRouter);
router.use("/users", usersOnboardingRouter);
router.use("/users", usersContactsRouter);
router.use("/moderation", moderationRouter);
router.use("/did", didRouter);
router.use("/stories", storiesRouter);
router.use("/comments", commentsRouter);
router.use("/storage", storageRouter);
router.use("/feed", feedRouter);
router.use("/vibe", vibeRouter);
router.use("/vibe-requests", vibeRequestsRouter);
router.use("/vibe-rooms", vibeRoomsRouter);
router.use("/snaps", snapsRouter);
router.use("/rewards", rewardsRouter);
router.use("/analytics", analyticsRouter);
router.use("/ads", adsRouter);
router.use("/live", liveRouter);
router.use("/sounds", soundsRouter);
router.use("/couple", coupleRouter);
router.use("/couple-feed", coupleFeedRouter);

export default router;
